# Generated by Django 6.0.6 on 2026-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gender', models.CharField(max_length=5)),
                ('ethnic_group', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('english_grade', models.CharField()),
                ('math_grade', models.CharField()),
                ('sciences_grade', models.CharField()),
                ('language_grade', models.CharField()),
                ('protfolio_rating', models.CharField()),
                ('coverletter_rating', models.CharField()),
                ('refletter_rating', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
