# Generated by Django 6.0.6 on 2026-06-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_student_data_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='protfolio_rating',
            new_name='portfolio_rating',
        ),
    ]
